### ISSUE TITLE
Backend Alerts to user

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-functions#11]
Hi @dereklieu just a question, if we have any feature that can alert the admin users in case any of the back end profiles, service and/or systems are down (for example Elastic Search)?

**Comment by dereklieu** [comment]
@guipizzini right now there are usage alerts where the database will notify you if it's running above a threshold CPU or memory limit (you may have gotten one or two already from bulk imports). The API and Elasticsearch VMs don't currently have this set up though. As far as I know there's no built-in option, since if a machine crashes it can't normally send emails. 

A potential item for a later phase is to set up a service that pings each machine at fixed intervals to test for readiness, and send an email if it takes too long to respond.
